# Generated by Django 3.2 on 2021-04-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_course', models.CharField(max_length=128)),
                ('date_start', models.DateField(null=True)),
                ('date_end', models.DateField(null=True)),
                ('quantity', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_category', models.CharField(max_length=128)),
                ('course', models.ManyToManyField(to='catalogs.Course')),
            ],
        ),
    ]
