# Generated by Django 3.2 on 2021-04-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Catalog',
        ),
    ]
