# Generated by Django 3.2 on 2021-04-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_rename_category_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
