# Generated by Django 3.2 on 2021-05-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_auto_20210427_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_category', models.CharField(max_length=128)),
                ('course', models.ManyToManyField(to='catalogs.Course')),
            ],
        ),
    ]
